language: node_js

node_js:
  - 10.8
  
addons:
  apt:
    packages:
    - libgconf-2-4

cache:
  directories:
    - ~/.npm
    - ~/.cache
  override:
    - npm ci
    - npm run cy:verify

jobs:
  include:
     - stage: Amazon tests
       script:
         - npm run run:amazon:tests
         - kill $(jobs -p) || true
     - stage: Api tests
       script:
         - npm run start
         - kill $(jobs -p) || true
