version: 2.1

jobs:         
  run-amazon-tests:
      docker:
        - image: cypress/base:14.16.0
      parallelism: 2  
      steps:
        - checkout 
        - run:
            command: | 
              npm install
              runId=$(npx testrail-start-run)
              echo "TestRail run id ${runId}"
              echo ${runId} > runId.txt
              echo "Saved file runId.txt"
              cat runId.txt
              ls -la && cat runId.txt
              npx percy exec -- cypress run --config-file cypress_amazon.json --spec 'cypress/integration/amazonTests/**.*'
              npx percy build:finalize -v
              npx percy build:wait --project 3ad2d9a6/galins-demo --commit $CIRCLE_SHA1 --fail-on-changes
              npx testrail-close-run
              
  run-google-tests:
      docker:
        - image: cypress/base:14.16.0
      steps:
        - checkout 
        - run:
            command: | 
              npm install
              runId=$(npx testrail-start-run)
              echo "TestRail run id ${runId}"
              echo ${runId} > runId.txt
              echo "Saved file runId.txt"
              cat runId.txt
              ls -la && cat runId.txt
              npx cypress run --config-file cypress.json --spec 'cypress/integration/google-store-tests/**.*'
              npx testrail-close-run             
          
      
workflows:
  build:
    jobs:
      - run-amazon-tests
      - run-google-tests
       
