version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          name: Production tests
          spec: cypress/integration/amazonTests/*
          config-file: cypress_amazon.json
          filters:
              branches:
                only:
                  - circleciintegration