version: 2.1
orbs:
  cypress: cypress-io/cypress@1


jobs:
  start-test-run:
      docker:
        - image: cimg/node:17.1.0
      steps:
        - checkout 
        - run:
            command: | 
              npm intstall
               runId=$(npx testrail-start-run \
              "Testing on Circle workflow ${CIRCLE_WORKFLOW_ID}" \
              "Cypress tests on CircleCI ${CIRCLE_BUILD_URL}")
              echo "TestRail run id ${runId}"
              echo ${runId} > runId.txt
              echo "Saved file runId.txt"
              cat runId.txt

  close-test-run:
      docker:
        - image: cimg/node:17.1.0
      steps:
        - checkout 
        - run:
            command: | 
              npx testrail-close-run
      
workflows:
  build:
    jobs:
      - start-test-run
      - cypress/run:
          name: Production tests
          spec: cypress/integration/amazonTests/*
          config-file: cypress_amazon.json
          filters:
              branches:
                only:
                  - circleciintegration
      - close-test-run           
