version: 2.1
orbs:
  cypress: cypress-io/cypress@1

workflows:

  tests_workflow:
    jobs:
      - run_tests

jobs:

run_tests:
    steps:
    - checkout
    - start_tests_step


command:

start_tests_step:
 description: Start tests
    steps:
            - run:
                name: Start tests
                command: |
                  npx cypress run --record --key 0d167392-db2d-44e0-931e-27f7dc0c6f9e --browser chrome
 