version: 2.1
orbs:
  cypress: cypress-io/cypress@1

workflows:

  tests_workflow:
    jobs:
      - run_tests

jobs:

  run_tests:
    steps:
    - checkout
    - start_tests_step


command:

start_tests_step:
 description: Start tests
    steps:
            - run:
                name: Start tests
                command: |
                  npx cypress run --config-file cypress_amazon.json --record --key 11595e38-7dce-415e-93e1-bcf5ab1ef0f9 --spec 'cypress/integration/amazonTests/**.*' --browser chrome
 