version: 2.1

jobs:
  start-test-run:
      docker:
        - image: cimg/node:17.1.0
      steps:
        - checkout 
        - run:
            command: | 
              npm install
              runId=$(npx testrail-start-run)
              echo "TestRail run id ${runId}"
              echo ${runId} > runId.txt
              echo "Saved file runId.txt"
              cat runId.txt
  
  run-tests:
      docker:
        - image: cypress/base:14.16.0
      steps:
        - run:
            command: | 
              npx cypress run --config-file cypress_amazon.json --spec 'cypress/integration/amazonTests/**.*'
          

  close-test-run:
      docker:
        - image: cimg/node:17.1.0
      steps:
        - run:
            command: |
              npx testrail-close-run
      
workflows:
  build:
    jobs:
      - start-test-run
      - run-tests:
           requires:
             - start-test-run
      - close-test-run:
           requires:
             - run-tests
       
